### ISSUE TITLE
Program crashes at end of video

### ISSUE THREAD

**Issue by jaybrecht** [jaybrecht/ENPM673-Project1#2]

**Comment by BrianBock** [comment]
What's the error? Does it crash on every video?

**Comment by jaybrecht** [comment]
Yeah, the while loop doesn't actually prevent python from trying to grab another frame after the last one. I think we can use the ret return for video.read(). That should return false if their isn't an available frame

**Comment by BrianBock** [comment]
this was fixed with 
if ret:
